// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCFX5K6UsPgRleLAvpr65gvxcT8l3Dyyk8',
//     appId: '1:573273331716:web:c866106a41dbd735d4bd51',
//     messagingSenderId: '573273331716',
//     projectId: 'event-cree',
//     authDomain: 'event-cree.firebaseapp.com',
//     storageBucket: 'event-cree.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyD-c_kHtwOEiv8pnrzqg4Pyxqfx0P7GCys',
//     appId: '1:573273331716:android:e4db84db1710dfe8d4bd51',
//     messagingSenderId: '573273331716',
//     projectId: 'event-cree',
//     storageBucket: 'event-cree.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBFKfc_001xAkN4Z9Z9ETpWg8XGEULnHUo',
//     appId: '1:573273331716:ios:962ea67639ac59abd4bd51',
//     messagingSenderId: '573273331716',
//     projectId: 'event-cree',
//     storageBucket: 'event-cree.appspot.com',
//     iosBundleId: 'com.example.getContacts',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBFKfc_001xAkN4Z9Z9ETpWg8XGEULnHUo',
//     appId: '1:573273331716:ios:a959bf7258f3ce3bd4bd51',
//     messagingSenderId: '573273331716',
//     projectId: 'event-cree',
//     storageBucket: 'event-cree.appspot.com',
//     iosBundleId: 'com.example.getContacts.RunnerTests',
//   );
// }
